import pyautogui
import time

pyautogui.press ("win")
time.sleep (1)
pyautogui.write ("notepad++")
time.sleep (1)
pyautogui.press ("enter")
time.sleep (1)
pyautogui.write ("Automatizar com PyAutoGUI é divertido!")
time.sleep (1)
pyautogui.moveTo (x=24, y=31)
time.sleep (1)
pyautogui.click (x=24, y=31)
time.sleep (1)
pyautogui.moveTo (x=67, y=213)
time.sleep (1)
pyautogui.click (x=67, y=213)
time.sleep (1)
pyautogui.moveTo (x=84, y=248)
time.sleep (2)
pyautogui.click (x=84, y=248)
time.sleep (2)
pyautogui.moveTo (x=796, y=558)
time.sleep (2)
pyautogui.click (x=796, y=558)
time.sleep (2)
pyautogui.hotkey ("alt","f4")